name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Show Forge version
        run: forge --version

      - name: Run Forge format check
        run: forge fmt --check
        id: fmt
        working-directory: src/contracts

      - name: Run Forge build
        run: forge build --sizes
        id: build
        working-directory: src/contracts

      - name: Run Forge tests
        run: forge test -vvv
        id: test
        working-directory: src/contracts
